### ISSUE TITLE
Dead project?

### ISSUE THREAD

**Issue by rejas** [alexyak/voicecontrol#10]
I do not know if work on this anymore. So I forked your repo since if anybody wants to check it out: https://github.com/rejas/MMM-MotionDetector

**Comment by skast96** [comment]
Does it do the same as this "dead" project cause I think a few ppl really need a fix :D

**Comment by rejas** [comment]
Darn, I did post this question in the wrong project, I ment your motiondetector project where I send you a PR and didnt get any reponse to it (see https://github.com/alexyak/motiondetector/pull/9) Sorry for my mixup, I didnt want to offend you.

**Comment by skast96** [comment]
Was this message meant to be for me, because you didnt offend me in any way. I just want anyone to fix this issue, because I am not able to do it :dango:

**Comment by rejas** [comment]
Note to self: Check the usernames of comments :-D Thought you were the original owner. Anyway, what issue do you need fixed?

**Comment by skast96** [comment]
No problemo :dango: 
The voicecontrol one cause I would use it for my magic mirror, if it is ever going to work :D

**Comment by rejas** [comment]
But which issue exactly? Can you give a link / issue number?
